ONE = COSINE_SIMILARITY
TWO = JACCARD_SIMILARITY
THREE = LEMMA_JACCARD_SIMILARITY
FUOR = COMBINED_SYNTACTIC

FIVE = PATH_SIMILARITY
SIX = WUP_SIMILARITY
SEVEN = COMBINED_SEMANTIC

EIGHT = SVM
NINE = LOGISTIC_REGRESSION


COSINE_SIMILARITY = "COSINE_SIMILARITY"
JACCARD_SIMILARITY = "JACCARD_SIMILARITY"
LEMMA_JACCARD_SIMILARITY = "LEMMA_JACCARD_SIMILARITY"
COMBINED_SYNTACTIC = "COMBINED_SYNTACTIC"
PATH_SIMILARITY = "PATH_SIMILARITY"
WUP_SIMILARITY = "WUP_SIMILARITY"
COMBINED_SEMANTIC = "COMBINED_SEMANTIC"
SVM = "SVM"
LOGISTIC_REGRESSION = "LOGISTIC_REGRESSION"
